<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JournalEntriesDetailsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('journal_entries_details')->truncate();

        $data = [
            [
                'id' => 305,
                'journal_entry_id' => 39,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 2000.00,
                'cost_center_id' => null,
                'description' => 'شحن فيزا رقم 9748',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 07:35:57',
                'updated_at' => '2025-11-12 07:35:57',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 306,
                'journal_entry_id' => 39,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 2000.00,
                'cost_center_id' => null,
                'description' => 'شحن فيزا رقم 1705',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 07:35:57',
                'updated_at' => '2025-11-12 07:35:57',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 307,
                'journal_entry_id' => 39,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 2000.00,
                'cost_center_id' => null,
                'description' => 'شحن فيزا رقم 9726',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 07:35:57',
                'updated_at' => '2025-11-12 07:35:57',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 308,
                'journal_entry_id' => 40,
                'account_id' => 308,
                'debit' => 2000.00,
                'credit' => 0.00,
                'cost_center_id' => null,
                'description' => 'شحن فيزا رقم 9748',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 07:37:34',
                'updated_at' => '2025-11-12 07:37:34',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 309,
                'journal_entry_id' => 40,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 2000.00,
                'cost_center_id' => null,
                'description' => 'شحن فيزا رقم 9748',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 07:37:34',
                'updated_at' => '2025-11-12 07:37:34',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 310,
                'journal_entry_id' => 40,
                'account_id' => 151,
                'debit' => 5700.00,
                'credit' => 0.00,
                'cost_center_id' => null,
                'description' => 'ايراد من العميل محمد',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 07:37:34',
                'updated_at' => '2025-11-12 07:37:34',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 311,
                'journal_entry_id' => 40,
                'account_id' => 304,
                'debit' => 0.00,
                'credit' => 5700.00,
                'cost_center_id' => null,
                'description' => 'ايراد من العميل محمد',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 07:37:34',
                'updated_at' => '2025-11-12 07:37:34',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 312,
                'journal_entry_id' => 41,
                'account_id' => 307,
                'debit' => 2000.00,
                'credit' => 0.00,
                'cost_center_id' => null,
                'description' => 'عهدة فيزا 9151 - شحن',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 15:42:05',
                'updated_at' => '2025-11-12 15:42:05',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 313,
                'journal_entry_id' => 41,
                'account_id' => 308,
                'debit' => 2000.00,
                'credit' => 0.00,
                'cost_center_id' => null,
                'description' => 'عهدة فيزا 9151 - شحن',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 15:42:05',
                'updated_at' => '2025-11-12 15:42:05',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 314,
                'journal_entry_id' => 41,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 2000.00,
                'cost_center_id' => null,
                'description' => 'عهدة فيزا 9151 - شحن',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 15:42:05',
                'updated_at' => '2025-11-12 15:42:05',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 315,
                'journal_entry_id' => 41,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 2000.00,
                'cost_center_id' => null,
                'description' => 'عهدة فيزا 9151 - شحن',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 15:42:05',
                'updated_at' => '2025-11-12 15:42:05',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 316,
                'journal_entry_id' => 42,
                'account_id' => 346,
                'debit' => 1500.00,
                'credit' => 0.00,
                'cost_center_id' => 16,
                'description' => 'مؤسسه خيال الزاهر - فك وتركيب زجاج لمكتب الجديد الربوه تعديل مكتب ابوسلطان وغرفة الاجتماعات الإجمالي 2875 تحويل 1500 ريال',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 15:44:18',
                'updated_at' => '2025-11-12 15:44:18',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 317,
                'journal_entry_id' => 42,
                'account_id' => 349,
                'debit' => 1.15,
                'credit' => 0.00,
                'cost_center_id' => 20,
                'description' => 'عمولات بنكية',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 15:44:18',
                'updated_at' => '2025-11-12 15:44:18',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 318,
                'journal_entry_id' => 42,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 1500.00,
                'cost_center_id' => null,
                'description' => 'مؤسسه خيال الزاهر - فك وتركيب زجاج لمكتب الجديد الربوه تعديل مكتب ابوسلطان وغرفة الاجتماعات الإجمالي 2875 تحويل 1500 ريال',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 15:44:18',
                'updated_at' => '2025-11-12 15:44:18',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 319,
                'journal_entry_id' => 42,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 1.15,
                'cost_center_id' => null,
                'description' => 'عمولات بنكية',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 15:44:18',
                'updated_at' => '2025-11-12 15:44:18',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 320,
                'journal_entry_id' => 42,
                'account_id' => 206,
                'debit' => 2500.00,
                'credit' => 0.00,
                'cost_center_id' => 20,
                'description' => 'خالد حويشي - تحويل 2500 ريال رسوم انهاء معاملة جمال من مكتب العمل',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 15:44:18',
                'updated_at' => '2025-11-12 15:44:18',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 321,
                'journal_entry_id' => 42,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 2500.00,
                'cost_center_id' => null,
                'description' => 'خالد حويشي - تحويل 2500 ريال رسوم انهاء معاملة جمال من مكتب العمل',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 15:44:18',
                'updated_at' => '2025-11-12 15:44:18',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 322,
                'journal_entry_id' => 43,
                'account_id' => 151,
                'debit' => 164545.88,
                'credit' => 0.00,
                'cost_center_id' => null,
                'description' => 'دفعة من مساند',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 15:47:03',
                'updated_at' => '2025-11-12 15:47:03',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 323,
                'journal_entry_id' => 43,
                'account_id' => 364,
                'debit' => 0.00,
                'credit' => 164545.88,
                'cost_center_id' => null,
                'description' => 'دفعة من مساند',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 15:47:03',
                'updated_at' => '2025-11-12 15:47:03',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 324,
                'journal_entry_id' => 43,
                'account_id' => 307,
                'debit' => 2000.00,
                'credit' => 0.00,
                'cost_center_id' => null,
                'description' => 'عهدة فيزا 9151 - عهدة',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 15:47:03',
                'updated_at' => '2025-11-12 15:47:03',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 325,
                'journal_entry_id' => 43,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 2000.00,
                'cost_center_id' => null,
                'description' => 'عهدة فيزا 9151 - عهدة',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 15:47:03',
                'updated_at' => '2025-11-12 15:47:03',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 326,
                'journal_entry_id' => 43,
                'account_id' => 151,
                'debit' => 300.00,
                'credit' => 0.00,
                'cost_center_id' => null,
                'description' => 'ايراد من العميل محمد',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 15:47:03',
                'updated_at' => '2025-11-12 15:47:03',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 327,
                'journal_entry_id' => 43,
                'account_id' => 304,
                'debit' => 0.00,
                'credit' => 300.00,
                'cost_center_id' => null,
                'description' => 'ايراد من العميل محمد',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 15:47:03',
                'updated_at' => '2025-11-12 15:47:03',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 328,
                'journal_entry_id' => 44,
                'account_id' => 176,
                'debit' => 25020.00,
                'credit' => 0.00,
                'cost_center_id' => 20,
                'description' => 'سداد فاتورة مكتب نيشن سريلانكا',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:10:48',
                'updated_at' => '2025-11-12 16:10:48',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 329,
                'journal_entry_id' => 44,
                'account_id' => 349,
                'debit' => 18.40,
                'credit' => 0.00,
                'cost_center_id' => 20,
                'description' => 'عمولات بنكية',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:10:48',
                'updated_at' => '2025-11-12 16:10:48',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 330,
                'journal_entry_id' => 44,
                'account_id' => 155,
                'debit' => 18000.00,
                'credit' => 0.00,
                'cost_center_id' => null,
                'description' => 'دعم بنك الانماء سداد جزء من فاتورة مكتب قولدن سيزون اثيوبيا',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:10:48',
                'updated_at' => '2025-11-12 16:10:48',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 331,
                'journal_entry_id' => 44,
                'account_id' => 349,
                'debit' => 1.15,
                'credit' => 0.00,
                'cost_center_id' => 20,
                'description' => 'عمولات بنكية',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:10:48',
                'updated_at' => '2025-11-12 16:10:48',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 332,
                'journal_entry_id' => 44,
                'account_id' => 155,
                'debit' => 19000.00,
                'credit' => 0.00,
                'cost_center_id' => null,
                'description' => 'دعم بنك الانماء سداد جزء من فاتورة مكتب قولدن سيزون اثيوبيا',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:10:48',
                'updated_at' => '2025-11-12 16:10:48',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 333,
                'journal_entry_id' => 44,
                'account_id' => 349,
                'debit' => 1.15,
                'credit' => 0.00,
                'cost_center_id' => 20,
                'description' => 'عمولات بنكية',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:10:48',
                'updated_at' => '2025-11-12 16:10:48',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 334,
                'journal_entry_id' => 44,
                'account_id' => 155,
                'debit' => 12890.00,
                'credit' => 0.00,
                'cost_center_id' => null,
                'description' => 'دعم بنك الانماء سداد جزء من فاتورة مكتب قولدن سيزون اثيوبيا',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:10:48',
                'updated_at' => '2025-11-12 16:10:48',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 335,
                'journal_entry_id' => 44,
                'account_id' => 349,
                'debit' => 1.15,
                'credit' => 0.00,
                'cost_center_id' => 20,
                'description' => 'عمولات بنكية',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:10:48',
                'updated_at' => '2025-11-12 16:10:48',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 336,
                'journal_entry_id' => 44,
                'account_id' => 301,
                'debit' => 1500.00,
                'credit' => 0.00,
                'cost_center_id' => null,
                'description' => ''محمد رشاد - محاسب قانوني تحويل مبلغ 1500 ريال راتب شهر سبتمبر (ملف الضرائب',
            ],
            [
                'id' => 337,
                'journal_entry_id' => 44,
                'account_id' => 367,
                'debit' => 7670.00,
                'credit' => 0.00,
                'cost_center_id' => 19,
                'description' => 'جواهر عايد ذعذاع العنزي - استرجاع تسفير - تم تسفير العاملة داخل الضمان وتم خصم العاملة + التذكرة من مكتب سنترال بنجلادش',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:10:48',
                'updated_at' => '2025-11-12 16:10:48',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 338,
                'journal_entry_id' => 44,
                'account_id' => 333,
                'debit' => 6000.00,
                'credit' => 0.00,
                'cost_center_id' => 19,
                'description' => 'نايف محمد شويحط - ايجار سكن عاملات مكتب المتميز - من 01-10-2025 حتي31-12-2025 تم تغيير العقد الإجمالي 24000 ريال',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:10:48',
                'updated_at' => '2025-11-12 16:10:48',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 339,
                'journal_entry_id' => 44,
                'account_id' => 365,
                'debit' => 950.00,
                'credit' => 0.00,
                'cost_center_id' => 19,
                'description' => 'ابوصقر - استلام 9 + 12 عاملة مرسلين من الحفر الي عرعر + ارسال عاملة الي الحفر',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:10:48',
                'updated_at' => '2025-11-12 16:10:48',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 340,
                'journal_entry_id' => 44,
                'account_id' => 176,
                'debit' => 53206.32,
                'credit' => 0.00,
                'cost_center_id' => 20,
                'description' => 'سداد فاتورة مكتب رفيق بنجلادش',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:10:48',
                'updated_at' => '2025-11-12 16:10:48',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 341,
                'journal_entry_id' => 44,
                'account_id' => 176,
                'debit' => 8135.20,
                'credit' => 0.00,
                'cost_center_id' => 20,
                'description' => 'سداد فاتورة مكتب كريستال اوغندا',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:10:48',
                'updated_at' => '2025-11-12 16:10:48',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 342,
                'journal_entry_id' => 44,
                'account_id' => 176,
                'debit' => 2965.20,
                'credit' => 0.00,
                'cost_center_id' => 20,
                'description' => 'سداد فاتورة مكتب ماجوردمو كينيا',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:10:48',
                'updated_at' => '2025-11-12 16:10:48',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 343,
                'journal_entry_id' => 44,
                'account_id' => 349,
                'debit' => 5.75,
                'credit' => 0.00,
                'cost_center_id' => 20,
                'description' => 'عمولات بنكية',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:10:48',
                'updated_at' => '2025-11-12 16:10:48',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 344,
                'journal_entry_id' => 44,
                'account_id' => 367,
                'debit' => 3800.00,
                'credit' => 0.00,
                'cost_center_id' => 16,
                'description' => 'حنين احمد محمد الجيزاني - استرجاع نقل - العامله معروضه نقل في مكتب الرياض والعميل موقع علي إقرار نقل',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:10:48',
                'updated_at' => '2025-11-12 16:10:48',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 345,
                'journal_entry_id' => 44,
                'account_id' => 349,
                'debit' => 1.15,
                'credit' => 0.00,
                'cost_center_id' => 20,
                'description' => 'عمولات بنكية',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:10:48',
                'updated_at' => '2025-11-12 16:10:48',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 346,
                'journal_entry_id' => 44,
                'account_id' => 331,
                'debit' => 9000.00,
                'credit' => 0.00,
                'cost_center_id' => 19,
                'description' => 'ايجار مكتب المتميز سداد دفعه 9000 ريال عن 3 شهور من 01-10-2025 حتي31-12-2025علما بان الايجار السنوي 36000 ريال',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:10:48',
                'updated_at' => '2025-11-12 16:10:48',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 347,
                'journal_entry_id' => 44,
                'account_id' => 349,
                'debit' => 1.15,
                'credit' => 0.00,
                'cost_center_id' => 20,
                'description' => 'عمولات بنكية',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:10:48',
                'updated_at' => '2025-11-12 16:10:48',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 348,
                'journal_entry_id' => 44,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 25020.00,
                'cost_center_id' => null,
                'description' => 'سداد فاتورة مكتب نيشن سريلانكا',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:10:48',
                'updated_at' => '2025-11-12 16:10:48',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 349,
                'journal_entry_id' => 44,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 18.40,
                'cost_center_id' => null,
                'description' => 'عمولات بنكية',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:10:48',
                'updated_at' => '2025-11-12 16:10:48',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 350,
                'journal_entry_id' => 44,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 18000.00,
                'cost_center_id' => null,
                'description' => 'دعم بنك الانماء سداد جزء من فاتورة مكتب قولدن سيزون اثيوبيا',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:10:48',
                'updated_at' => '2025-11-12 16:10:48',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 351,
                'journal_entry_id' => 44,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 1.15,
                'cost_center_id' => null,
                'description' => 'عمولات بنكية',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:10:48',
                'updated_at' => '2025-11-12 16:10:48',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 352,
                'journal_entry_id' => 44,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 19000.00,
                'cost_center_id' => null,
                'description' => 'دعم بنك الانماء سداد جزء من فاتورة مكتب قولدن سيزون اثيوبيا',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:10:48',
                'updated_at' => '2025-11-12 16:10:48',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 353,
                'journal_entry_id' => 44,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 1.15,
                'cost_center_id' => null,
                'description' => 'عمولات بنكية',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:10:48',
                'updated_at' => '2025-11-12 16:10:48',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 354,
                'journal_entry_id' => 44,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 12890.00,
                'cost_center_id' => null,
                'description' => 'دعم بنك الانماء سداد جزء من فاتورة مكتب قولدن سيزون اثيوبيا',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:10:48',
                'updated_at' => '2025-11-12 16:10:48',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 355,
                'journal_entry_id' => 44,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 1.15,
                'cost_center_id' => null,
                'description' => 'عمولات بنكية',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:10:48',
                'updated_at' => '2025-11-12 16:10:48',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 356,
                'journal_entry_id' => 44,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 1500.00,
                'cost_center_id' => null,
                'description' => ''محمد رشاد - محاسب قانوني تحويل مبلغ 1500 ريال راتب شهر سبتمبر (ملف الضرائب',
            ],
            [
                'id' => 357,
                'journal_entry_id' => 44,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 7670.00,
                'cost_center_id' => null,
                'description' => 'جواهر عايد ذعذاع العنزي - استرجاع تسفير - تم تسفير العاملة داخل الضمان وتم خصم العاملة + التذكرة من مكتب سنترال بنجلادش',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:10:48',
                'updated_at' => '2025-11-12 16:10:48',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 358,
                'journal_entry_id' => 44,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 6000.00,
                'cost_center_id' => null,
                'description' => 'نايف محمد شويحط - ايجار سكن عاملات مكتب المتميز - من 01-10-2025 حتي31-12-2025 تم تغيير العقد الإجمالي 24000 ريال',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:10:48',
                'updated_at' => '2025-11-12 16:10:48',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 359,
                'journal_entry_id' => 44,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 950.00,
                'cost_center_id' => null,
                'description' => 'ابوصقر - استلام 9 + 12 عاملة مرسلين من الحفر الي عرعر + ارسال عاملة الي الحفر',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:10:48',
                'updated_at' => '2025-11-12 16:10:48',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 360,
                'journal_entry_id' => 44,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 64306.72,
                'cost_center_id' => null,
                'description' => 'سداد فاتورة مكتب رفيق بنجلادش',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:10:48',
                'updated_at' => '2025-11-12 16:10:48',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 361,
                'journal_entry_id' => 44,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 5.75,
                'cost_center_id' => null,
                'description' => 'عمولات بنكية',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:10:48',
                'updated_at' => '2025-11-12 16:10:48',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 362,
                'journal_entry_id' => 44,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 3800.00,
                'cost_center_id' => null,
                'description' => 'حنين احمد محمد الجيزاني - استرجاع نقل - العامله معروضه نقل في مكتب الرياض والعميل موقع علي إقرار نقل',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:10:48',
                'updated_at' => '2025-11-12 16:10:48',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 363,
                'journal_entry_id' => 44,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 1.15,
                'cost_center_id' => null,
                'description' => 'عمولات بنكية',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:10:48',
                'updated_at' => '2025-11-12 16:10:48',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 364,
                'journal_entry_id' => 44,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 9000.00,
                'cost_center_id' => null,
                'description' => 'ايجار مكتب المتميز سداد دفعه 9000 ريال عن 3 شهور من 01-10-2025 حتي31-12-2025علما بان الايجار السنوي 36000 ريال',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:10:48',
                'updated_at' => '2025-11-12 16:10:48',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 365,
                'journal_entry_id' => 44,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 1.15,
                'cost_center_id' => null,
                'description' => 'عمولات بنكية',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:10:48',
                'updated_at' => '2025-11-12 16:10:48',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 366,
                'journal_entry_id' => 45,
                'account_id' => 151,
                'debit' => 131666.50,
                'credit' => 0.00,
                'cost_center_id' => null,
                'description' => 'دفعة من مساند',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:37:38',
                'updated_at' => '2025-11-12 16:37:38',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 367,
                'journal_entry_id' => 45,
                'account_id' => 364,
                'debit' => 0.00,
                'credit' => 131666.50,
                'cost_center_id' => null,
                'description' => 'دفعة من مساند',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:37:38',
                'updated_at' => '2025-11-12 16:37:38',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 368,
                'journal_entry_id' => 45,
                'account_id' => 349,
                'debit' => 37.38,
                'credit' => 0.00,
                'cost_center_id' => 20,
                'description' => 'رسوم وعمولات بنكية',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:37:38',
                'updated_at' => '2025-11-12 16:37:38',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 369,
                'journal_entry_id' => 45,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 37.38,
                'cost_center_id' => null,
                'description' => 'رسوم وعمولات بنكية',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:37:38',
                'updated_at' => '2025-11-12 16:37:38',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 370,
                'journal_entry_id' => 45,
                'account_id' => 151,
                'debit' => 1270.00,
                'credit' => 0.00,
                'cost_center_id' => null,
                'description' => 'ايراد من العميلة خلود',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:37:38',
                'updated_at' => '2025-11-12 16:37:38',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 371,
                'journal_entry_id' => 45,
                'account_id' => 304,
                'debit' => 0.00,
                'credit' => 1270.00,
                'cost_center_id' => null,
                'description' => 'ايراد من العميلة خلود',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:37:38',
                'updated_at' => '2025-11-12 16:37:38',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 372,
                'journal_entry_id' => 46,
                'account_id' => 365,
                'debit' => 317.00,
                'credit' => 0.00,
                'cost_center_id' => 18,
                'description' => 'ابوفواز - تحويل رسوم استلام عاملات من شركة سلسك الدمام 167 ريال +رسوم المندوب 150 ريال اماني رمضان الظفيري',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:50:41',
                'updated_at' => '2025-11-12 16:50:41',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 373,
                'journal_entry_id' => 46,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 317.00,
                'cost_center_id' => 18,
                'description' => 'ابوفواز - تحويل رسوم استلام عاملات من شركة سلسك الدمام 167 ريال +رسوم المندوب 150 ريال اماني رمضان الظفيري',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:50:41',
                'updated_at' => '2025-11-12 16:50:41',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 374,
                'journal_entry_id' => 46,
                'account_id' => 347,
                'debit' => 2500.00,
                'credit' => 0.00,
                'cost_center_id' => 18,
                'description' => 'أبو فواز - شحن محفظة الدريس 2500 ريال اخر تحويل05-10',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:50:41',
                'updated_at' => '2025-11-12 16:50:41',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 375,
                'journal_entry_id' => 46,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 2500.00,
                'cost_center_id' => null,
                'description' => 'أبو فواز - شحن محفظة الدريس 2500 ريال اخر تحويل05-10',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:50:41',
                'updated_at' => '2025-11-12 16:50:41',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 376,
                'journal_entry_id' => 46,
                'account_id' => 366,
                'debit' => 950.00,
                'credit' => 0.00,
                'cost_center_id' => 18,
                'description' => 'وكالة نجد//تذكرة عاملة شويمي سعد شويمي السبيعي - داخل الضمان - تم خصم العاملة + التذكرة من مكتب سابولا اثيوبيا',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:50:41',
                'updated_at' => '2025-11-12 16:50:41',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 377,
                'journal_entry_id' => 46,
                'account_id' => 366,
                'debit' => 950.00,
                'credit' => 0.00,
                'cost_center_id' => 18,
                'description' => 'وكالة نجد//تذكرة عاملة شويمي سعد شويمي السبيعي - داخل الضمان - تم خصم العاملة + التذكرة من مكتب سابولا اثيوبيا',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:50:41',
                'updated_at' => '2025-11-12 16:50:41',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 378,
                'journal_entry_id' => 46,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 1900.00,
                'cost_center_id' => null,
                'description' => 'وكالة نجد//تذكرة عاملة هاجد مبرك عوض العازمي - داخل الضمان - تم خصم العاملة + التذكرة من مكتب قولدن سيزون اثيوبيا',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:50:41',
                'updated_at' => '2025-11-12 16:50:41',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 379,
                'journal_entry_id' => 46,
                'account_id' => 366,
                'debit' => 1600.00,
                'credit' => 0.00,
                'cost_center_id' => 19,
                'description' => 'ابوصقر- تذكرة عاملة اسامه بدر مطر ضاحي العنزي - تم خصم العاملة + التذكرة من مكتب ليلي الفلبين',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:50:41',
                'updated_at' => '2025-11-12 16:50:41',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 380,
                'journal_entry_id' => 46,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 1600.00,
                'cost_center_id' => null,
                'description' => 'ابوصقر- تذكرة عاملة اسامه بدر مطر ضاحي العنزي - تم خصم العاملة + التذكرة من مكتب ليلي الفلبين',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:50:41',
                'updated_at' => '2025-11-12 16:50:41',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 381,
                'journal_entry_id' => 46,
                'account_id' => 367,
                'debit' => 3779.00,
                'credit' => 0.00,
                'cost_center_id' => 19,
                'description' => 'فصايل محمد عوده الصلبي - استرجاع تسفير - تم تسفير العاملة داخل الضمان و تم خصم العاملة + التذكرة من مكتب قولدن سيزون اثيوبيا',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:50:41',
                'updated_at' => '2025-11-12 16:50:41',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 382,
                'journal_entry_id' => 46,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 3779.00,
                'cost_center_id' => null,
                'description' => 'سداد جزء من فاتورة مكتب قولدن سيزون اثيوبيا',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:50:41',
                'updated_at' => '2025-11-12 16:50:41',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 383,
                'journal_entry_id' => 46,
                'account_id' => 176,
                'debit' => 58209.44,
                'credit' => 0.00,
                'cost_center_id' => 20,
                'description' => 'سداد فاتورة مكتب ليلي الفلبين',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:50:41',
                'updated_at' => '2025-11-12 16:50:41',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 384,
                'journal_entry_id' => 46,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 58209.44,
                'cost_center_id' => null,
                'description' => 'سداد جزء من فاتورة مكتب قولدن سيزون اثيوبيا\r\n+ سداد فاتورة مكتب ليلي الفلبين',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:50:41',
                'updated_at' => '2025-11-12 16:50:41',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 385,
                'journal_entry_id' => 46,
                'account_id' => 349,
                'debit' => 5.75,
                'credit' => 0.00,
                'cost_center_id' => 20,
                'description' => 'عمولات بنكية',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:50:41',
                'updated_at' => '2025-11-12 16:50:41',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 386,
                'journal_entry_id' => 46,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 5.75,
                'cost_center_id' => null,
                'description' => 'عمولات بنكية',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:50:41',
                'updated_at' => '2025-11-12 16:50:41',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 387,
                'journal_entry_id' => 46,
                'account_id' => 346,
                'debit' => 1375.00,
                'credit' => 0.00,
                'cost_center_id' => 16,
                'description' => 'مؤسسه خيال الزاهر - فك وتركيب زجاج لمكتب الجديد الربوه تعديل مكتب ابوسلطان وغرفة الاجتماعات الإجمالي 2875 المتبقي 1375 ريال',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:50:41',
                'updated_at' => '2025-11-12 16:50:41',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 388,
                'journal_entry_id' => 46,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 1375.00,
                'cost_center_id' => null,
                'description' => 'مؤسسه خيال الزاهر - فك وتركيب زجاج لمكتب الجديد الربوه تعديل مكتب ابوسلطان وغرفة الاجتماعات الإجمالي 2875 المتبقي 1375 ريال',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:50:41',
                'updated_at' => '2025-11-12 16:50:41',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 389,
                'journal_entry_id' => 46,
                'account_id' => 349,
                'debit' => 1.15,
                'credit' => 0.00,
                'cost_center_id' => 20,
                'description' => 'عمولات بنكية',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:50:41',
                'updated_at' => '2025-11-12 16:50:41',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 390,
                'journal_entry_id' => 46,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 1.15,
                'cost_center_id' => null,
                'description' => 'عمولات بنكية',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:50:41',
                'updated_at' => '2025-11-12 16:50:41',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 391,
                'journal_entry_id' => 47,
                'account_id' => 151,
                'debit' => 72437.30,
                'credit' => 0.00,
                'cost_center_id' => null,
                'description' => 'دفعة من مساند',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:54:40',
                'updated_at' => '2025-11-12 16:54:40',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 392,
                'journal_entry_id' => 47,
                'account_id' => 364,
                'debit' => 0.00,
                'credit' => 72437.30,
                'cost_center_id' => null,
                'description' => 'دفعة من مساند',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:54:40',
                'updated_at' => '2025-11-12 16:54:40',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 393,
                'journal_entry_id' => 47,
                'account_id' => 308,
                'debit' => 2000.00,
                'credit' => 0.00,
                'cost_center_id' => null,
                'description' => 'عهدة فيزا 9748 - شحن',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:54:40',
                'updated_at' => '2025-11-12 16:54:40',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 394,
                'journal_entry_id' => 47,
                'account_id' => 310,
                'debit' => 2000.00,
                'credit' => 0.00,
                'cost_center_id' => null,
                'description' => 'عهدة فيزا 9726- شحن',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:54:40',
                'updated_at' => '2025-11-12 16:54:40',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 395,
                'journal_entry_id' => 47,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 2000.00,
                'cost_center_id' => null,
                'description' => 'عهدة فيزا 9748 - شحن',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:54:40',
                'updated_at' => '2025-11-12 16:54:40',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 396,
                'journal_entry_id' => 47,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 2000.00,
                'cost_center_id' => null,
                'description' => 'عهدة فيزا 9726- شحن',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:54:40',
                'updated_at' => '2025-11-12 16:54:40',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 397,
                'journal_entry_id' => 47,
                'account_id' => 151,
                'debit' => 10000.00,
                'credit' => 0.00,
                'cost_center_id' => null,
                'description' => 'ايراد من العميل سعود',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:54:40',
                'updated_at' => '2025-11-12 16:54:40',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 398,
                'journal_entry_id' => 47,
                'account_id' => 304,
                'debit' => 0.00,
                'credit' => 10000.00,
                'cost_center_id' => null,
                'description' => 'ايراد من العميل سعود',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 16:54:40',
                'updated_at' => '2025-11-12 16:54:40',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 399,
                'journal_entry_id' => 48,
                'account_id' => 342,
                'debit' => 600.00,
                'credit' => 0.00,
                'cost_center_id' => 18,
                'description' => 'فاطمه عطيه حزيم العنزي - سداد الإقامة - العاملة نقل الي العميل حنان حليس الشمري مسدد 2000 ريال باقي 7000 تم اصدار كمبيالة',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 17:10:14',
                'updated_at' => '2025-11-12 17:10:14',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 400,
                'journal_entry_id' => 48,
                'account_id' => 366,
                'debit' => 300.00,
                'credit' => 0.00,
                'cost_center_id' => 16,
                'description' => ''وكالة أسبوع الطيران - تذكرة سفر - عاملة يوسف سطام العنزي الي سكاكا العميل مسدد 10000 ريال باقي 9000 (سعود وارد الرويلي',
            ],
            [
                'id' => 401,
                'journal_entry_id' => 48,
                'account_id' => 338,
                'debit' => 115.00,
                'credit' => 0.00,
                'cost_center_id' => 16,
                'description' => 'خليل - سداد فاتورة جوال المكتب 115 ريال',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 17:10:14',
                'updated_at' => '2025-11-12 17:10:14',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 402,
                'journal_entry_id' => 48,
                'account_id' => 338,
                'debit' => 200.00,
                'credit' => 0.00,
                'cost_center_id' => 18,
                'description' => 'ابوفواز - سداد فاتورة جوال المكتب 200',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 17:10:14',
                'updated_at' => '2025-11-12 17:10:14',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 403,
                'journal_entry_id' => 48,
                'account_id' => 368,
                'debit' => 840.00,
                'credit' => 0.00,
                'cost_center_id' => 16,
                'description' => ''مندوبة الفلبين ANALYN FISHER - ادخال 3عقود للبولو1متميز +2 امتياز (عبدالله لواص+وليد العتيبي+خالد الريض',
            ],
            [
                'id' => 404,
                'journal_entry_id' => 48,
                'account_id' => 205,
                'debit' => 129.00,
                'credit' => 0.00,
                'cost_center_id' => 16,
                'description' => 'اسامه - ضيافه مكتب أبو ريان وتم الاتفاق معاه علي العمل مرة اخري علي 600 دولار',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 17:10:14',
                'updated_at' => '2025-11-12 17:10:14',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 405,
                'journal_entry_id' => 48,
                'account_id' => 338,
                'debit' => 230.00,
                'credit' => 0.00,
                'cost_center_id' => 16,
                'description' => 'اسامه - سداد فاتورة جوال المكتب 230 ريال',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 17:10:14',
                'updated_at' => '2025-11-12 17:10:14',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 406,
                'journal_entry_id' => 48,
                'account_id' => 176,
                'debit' => 49890.00,
                'credit' => 0.00,
                'cost_center_id' => 20,
                'description' => 'سداد باقي فاتورة مكتب قولدن سيزون اثيوبيا',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 17:10:14',
                'updated_at' => '2025-11-12 17:10:14',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 407,
                'journal_entry_id' => 48,
                'account_id' => 349,
                'debit' => 5.75,
                'credit' => 0.00,
                'cost_center_id' => 20,
                'description' => 'عمولات بنكية',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 17:10:14',
                'updated_at' => '2025-11-12 17:10:14',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 408,
                'journal_entry_id' => 48,
                'account_id' => 151,
                'debit' => 115.00,
                'credit' => 0.00,
                'cost_center_id' => null,
                'description' => 'عمران - سداد فاتورة جوال المكتب 115 ريال',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 17:10:14',
                'updated_at' => '2025-11-12 17:10:14',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 409,
                'journal_entry_id' => 48,
                'account_id' => 151,
                'debit' => 0.58,
                'credit' => 0.00,
                'cost_center_id' => null,
                'description' => 'عمولات بنكية',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 17:10:14',
                'updated_at' => '2025-11-12 17:10:14',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 410,
                'journal_entry_id' => 48,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 600.00,
                'cost_center_id' => null,
                'description' => 'فاطمه عطيه حزيم العنزي - سداد الإقامة - العاملة نقل الي العميل حنان حليس الشمري مسدد 2000 ريال باقي 7000 تم اصدار كمبيالة',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 17:10:14',
                'updated_at' => '2025-11-12 17:10:14',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 411,
                'journal_entry_id' => 48,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 300.00,
                'cost_center_id' => null,
                'description' => ''وكالة أسبوع الطيران - تذكرة سفر - عاملة يوسف سطام العنزي الي سكاكا العميل مسدد 10000 ريال باقي 9000 (سعود وارد الرويلي',
            ],
            [
                'id' => 412,
                'journal_entry_id' => 48,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 115.00,
                'cost_center_id' => null,
                'description' => 'خليل - سداد فاتورة جوال المكتب 115 ريال',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 17:10:14',
                'updated_at' => '2025-11-12 17:10:14',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 413,
                'journal_entry_id' => 48,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 200.00,
                'cost_center_id' => null,
                'description' => 'ابوفواز - سداد فاتورة جوال المكتب 200',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 17:10:14',
                'updated_at' => '2025-11-12 17:10:14',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 414,
                'journal_entry_id' => 48,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 840.00,
                'cost_center_id' => null,
                'description' => ''مندوبة الفلبين ANALYN FISHER - ادخال 3عقود للبولو1متميز +2 امتياز (عبدالله لواص+وليد العتيبي+خالد الريض',
            ],
            [
                'id' => 415,
                'journal_entry_id' => 48,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 129.00,
                'cost_center_id' => null,
                'description' => 'اسامه - ضيافه مكتب أبو ريان وتم الاتفاق معاه علي العمل مرة اخري علي 600 دولار',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 17:10:14',
                'updated_at' => '2025-11-12 17:10:14',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 416,
                'journal_entry_id' => 48,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 230.00,
                'cost_center_id' => null,
                'description' => 'اسامه - سداد فاتورة جوال المكتب 230 ريال',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 17:10:14',
                'updated_at' => '2025-11-12 17:10:14',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 417,
                'journal_entry_id' => 48,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 49890.00,
                'cost_center_id' => null,
                'description' => 'سداد باقي فاتورة مكتب قولدن سيزون اثيوبيا',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 17:10:14',
                'updated_at' => '2025-11-12 17:10:14',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 418,
                'journal_entry_id' => 48,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 5.75,
                'cost_center_id' => null,
                'description' => 'عمولات بنكية',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 17:10:14',
                'updated_at' => '2025-11-12 17:10:14',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 419,
                'journal_entry_id' => 48,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 115.00,
                'cost_center_id' => null,
                'description' => 'عمران - سداد فاتورة جوال المكتب 115 ريال',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 17:10:14',
                'updated_at' => '2025-11-12 17:10:14',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => 420,
                'journal_entry_id' => 48,
                'account_id' => 151,
                'debit' => 0.00,
                'credit' => 0.58,
                'cost_center_id' => null,
                'description' => 'عمولات بنكية',
                'attachment_path' => null,
                'entry_date' => '2025-11-12',
                'asset_id' => null,
                'created_at' => '2025-11-12 17:10:14',
                'updated_at' => '2025-11-12 17:10:14',
                'deleted_at' => null,
                'reversal_of_detail_id' => null,
            ],
            [
                'id' => '`id` bigint(20',
            ],
            [
                'id' => 20,
            ],
            [
                'id' => 20,
            ],
            [
                'id' => 20,
            ],
            [
                'id' => 20,
            ],
            [
                'id' => 20,
            ],
            [
                'id' => 190,
            ],
            [
                'id' => 190,
            ],
            [
                'id' => 190,
            ],
            [
                'id' => 10,
            ],
            [
                'id' => 40,
            ],
            [
                'id' => 60,
            ],
            [
                'id' => 'concat(ifnull(`country_code`',
                'journal_entry_id' => '',
            ],
            [
                'id' => '`phone`',
                'journal_entry_id' => '',
            ],
            [
                'id' => 40,
            ],
            [
                'id' => 18,
                'journal_entry_id' => 2,
            ],
            [
                'id' => 3,
            ],
            [
                'id' => 4,
            ],
            [
                'id' => 1,
            ],
        ];

        foreach ($data as $row) {
            DB::table('journal_entries_details')->insert($row);
        }

        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
