<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JournalEntriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('journal_entries')->truncate();

        $data = [
            [
                'id' => 1,
                'entry_date' => '2025-01-01',
                'reference' => 'OB-20250911-182000-YIL8',
                'description' => 'رصيد افتتاحي',
                'created_by' => 160,
                'payment_voucher_id' => null,
                'type' => '1',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-09-11 18:20:00',
                'updated_at' => '2025-09-13 14:40:16',
                'deleted_at' => '2025-09-13 14:40:16',
                'reversal_of_id' => null,
                'head_date' => '2025-09-11 15:20:00',
                'ref' => null,
            ],
            [
                'id' => 2,
                'entry_date' => '2025-01-01',
                'reference' => 'OB-20250911-183107-Q0S9',
                'description' => 'رصيد افتتاحي',
                'created_by' => 160,
                'payment_voucher_id' => null,
                'type' => '1',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-09-11 18:31:07',
                'updated_at' => '2025-09-13 14:40:38',
                'deleted_at' => '2025-09-13 14:40:38',
                'reversal_of_id' => null,
                'head_date' => '2025-09-11 15:31:07',
                'ref' => null,
            ],
            [
                'id' => 3,
                'entry_date' => '2025-09-12',
                'reference' => null,
                'description' => 'صص',
                'created_by' => 163,
                'payment_voucher_id' => null,
                'type' => 'entry',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-09-12 14:24:05',
                'updated_at' => '2025-09-12 14:30:32',
                'deleted_at' => '2025-09-12 14:30:32',
                'reversal_of_id' => null,
                'head_date' => '2025-09-12 11:24:05',
                'ref' => null,
            ],
            [
                'id' => 4,
                'entry_date' => '2025-09-13',
                'reference' => null,
                'description' => 'تست',
                'created_by' => 163,
                'payment_voucher_id' => null,
                'type' => 'entry',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-09-13 15:40:13',
                'updated_at' => '2025-09-13 16:01:53',
                'deleted_at' => '2025-09-13 16:01:53',
                'reversal_of_id' => null,
                'head_date' => '2025-09-13 12:40:13',
                'ref' => null,
            ],
            [
                'id' => 5,
                'entry_date' => '2025-11-01',
                'reference' => null,
                'description' => 'حوالة ايراد مساند',
                'created_by' => 160,
                'payment_voucher_id' => null,
                'type' => 'entry',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-11-12 03:06:22',
                'updated_at' => '2025-11-12 03:09:14',
                'deleted_at' => '2025-11-12 03:09:14',
                'reversal_of_id' => null,
                'head_date' => '2025-11-12 00:06:22',
                'ref' => null,
            ],
            [
                'id' => 6,
                'entry_date' => '2025-01-10',
                'reference' => null,
                'description' => 'حوالة ايراد مساند',
                'created_by' => 160,
                'payment_voucher_id' => null,
                'type' => 'entry',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-11-12 03:10:06',
                'updated_at' => '2025-11-12 03:10:06',
                'deleted_at' => null,
                'reversal_of_id' => null,
                'head_date' => '2025-11-12 00:10:06',
                'ref' => null,
            ],
            [
                'id' => 7,
                'entry_date' => '2025-01-10',
                'reference' => null,
                'description' => 'ايراد من الاستقدام عوض',
                'created_by' => 160,
                'payment_voucher_id' => null,
                'type' => 'entry',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-11-12 03:12:46',
                'updated_at' => '2025-11-12 03:12:46',
                'deleted_at' => null,
                'reversal_of_id' => null,
                'head_date' => '2025-11-12 00:12:46',
                'ref' => null,
            ],
            [
                'id' => 8,
                'entry_date' => '2025-10-01',
                'reference' => null,
                'description' => 'ياسمين علي هادي - استلام سلسك - رسوم استلام عاملة هدي احمد عطيه بجازان 200 اتعاب المندوب + 239 قيمة التذكرة',
                'created_by' => 160,
                'payment_voucher_id' => null,
                'type' => 'entry',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-11-12 03:34:44',
                'updated_at' => '2025-11-12 03:34:44',
                'deleted_at' => null,
                'reversal_of_id' => null,
                'head_date' => '2025-11-12 00:34:44',
                'ref' => null,
            ],
            [
                'id' => 9,
                'entry_date' => '2025-10-01',
                'reference' => null,
                'description' => 'شحن نت سكن العاملات مكتب المتميز 287.5 ريال',
                'created_by' => 160,
                'payment_voucher_id' => null,
                'type' => 'entry',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-11-12 03:35:59',
                'updated_at' => '2025-11-12 03:35:59',
                'deleted_at' => null,
                'reversal_of_id' => null,
                'head_date' => '2025-11-12 00:35:59',
                'ref' => null,
            ],
            [
                'id' => 10,
                'entry_date' => '2025-10-01',
                'reference' => null,
                'description' => 'ابوفواز - ارسال عامله من الحفر الي الرياض -اثيوبيا عاملة ملاك محمد الشمري',
                'created_by' => 160,
                'payment_voucher_id' => null,
                'type' => 'entry',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-11-12 03:40:05',
                'updated_at' => '2025-11-12 03:40:05',
                'deleted_at' => null,
                'reversal_of_id' => null,
                'head_date' => '2025-11-12 00:40:05',
                'ref' => null,
            ],
            [
                'id' => 11,
                'entry_date' => '2025-10-01',
                'reference' => null,
                'description' => 'بدريه خيران عيفان الرشيدي - مطالبة مالية - تمت المفاهمه مع العميل ومستمر معنا وتخصم الغرامة علي مكتب سنترال بنجلادش',
                'created_by' => 160,
                'payment_voucher_id' => null,
                'type' => 'entry',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-11-12 03:42:58',
                'updated_at' => '2025-11-12 03:42:58',
                'deleted_at' => null,
                'reversal_of_id' => null,
                'head_date' => '2025-11-12 00:42:58',
                'ref' => null,
            ],
            [
                'id' => 12,
                'entry_date' => '2025-10-01',
                'reference' => null,
                'description' => 'ابوصقر - استلام 23 عاملة مرسلين من الحفر الي عرعر + ارسال عاملة الي الحفر',
                'created_by' => 160,
                'payment_voucher_id' => null,
                'type' => 'entry',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-11-12 03:46:53',
                'updated_at' => '2025-11-12 03:46:53',
                'deleted_at' => null,
                'reversal_of_id' => null,
                'head_date' => '2025-11-12 00:46:53',
                'ref' => null,
            ],
            [
                'id' => 13,
                'entry_date' => '2025-10-02',
                'reference' => null,
                'description' => 'ايراد من العميل فيصل',
                'created_by' => 160,
                'payment_voucher_id' => null,
                'type' => 'entry',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-11-12 03:50:10',
                'updated_at' => '2025-11-12 03:50:10',
                'deleted_at' => null,
                'reversal_of_id' => null,
                'head_date' => '2025-11-12 00:50:10',
                'ref' => null,
            ],
            [
                'id' => 14,
                'entry_date' => '2025-10-02',
                'reference' => null,
                'description' => 'عهدة البطاقة الائتمانية رقم 151',
                'created_by' => 160,
                'payment_voucher_id' => null,
                'type' => 'entry',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-11-12 03:51:57',
                'updated_at' => '2025-11-12 03:51:57',
                'deleted_at' => null,
                'reversal_of_id' => null,
                'head_date' => '2025-11-12 00:51:57',
                'ref' => null,
            ],
            [
                'id' => 15,
                'entry_date' => '2025-10-02',
                'reference' => null,
                'description' => 'فيصل قاسم بن محمد العنزي - سداد مساند - العميل مسدد 3500 ريال خصم خاص من ابوسلطان',
                'created_by' => 160,
                'payment_voucher_id' => null,
                'type' => 'entry',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-11-12 03:53:10',
                'updated_at' => '2025-11-12 03:53:10',
                'deleted_at' => null,
                'reversal_of_id' => null,
                'head_date' => '2025-11-12 00:53:10',
                'ref' => null,
            ],
            [
                'id' => 16,
                'entry_date' => '2025-10-02',
                'reference' => null,
                'description' => 'فيصل سالم سعيد القثمي - سداد الإقامة - العاملة معروضه نقل خدمات والعميل موقع علي إقرار نقل',
                'created_by' => 160,
                'payment_voucher_id' => null,
                'type' => 'entry',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-11-12 03:56:35',
                'updated_at' => '2025-11-12 03:56:35',
                'deleted_at' => null,
                'reversal_of_id' => null,
                'head_date' => '2025-11-12 00:56:35',
                'ref' => null,
            ],
            [
                'id' => 17,
                'entry_date' => '2025-10-05',
                'reference' => null,
                'description' => 'ايراد من العميلة غادة راشد',
                'created_by' => 160,
                'payment_voucher_id' => null,
                'type' => 'entry',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-11-12 03:57:39',
                'updated_at' => '2025-11-12 03:57:39',
                'deleted_at' => null,
                'reversal_of_id' => null,
                'head_date' => '2025-11-12 00:57:39',
                'ref' => null,
            ],
            [
                'id' => 18,
                'entry_date' => '2025-10-05',
                'reference' => null,
                'description' => 'عهدة فيزا 0236',
                'created_by' => 160,
                'payment_voucher_id' => null,
                'type' => 'entry',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-11-12 04:00:19',
                'updated_at' => '2025-11-12 04:00:19',
                'deleted_at' => null,
                'reversal_of_id' => null,
                'head_date' => '2025-11-12 01:00:19',
                'ref' => null,
            ],
            [
                'id' => 19,
                'entry_date' => '2025-10-05',
                'reference' => null,
                'description' => 'ابوفيصل - سداد فاتورة جوال المكتب',
                'created_by' => 160,
                'payment_voucher_id' => null,
                'type' => 'entry',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-11-12 04:08:50',
                'updated_at' => '2025-11-12 04:08:50',
                'deleted_at' => null,
                'reversal_of_id' => null,
                'head_date' => '2025-11-12 01:08:50',
                'ref' => null,
            ],
            [
                'id' => 20,
                'entry_date' => '2025-10-06',
                'reference' => null,
                'description' => 'دفعة من مساند',
                'created_by' => 160,
                'payment_voucher_id' => null,
                'type' => 'entry',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-11-12 04:14:05',
                'updated_at' => '2025-11-12 04:14:05',
                'deleted_at' => null,
                'reversal_of_id' => null,
                'head_date' => '2025-11-12 01:14:05',
                'ref' => null,
            ],
            [
                'id' => 21,
                'entry_date' => '2025-10-07',
                'reference' => null,
                'description' => 'دفعة من مساند',
                'created_by' => 160,
                'payment_voucher_id' => null,
                'type' => 'entry',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-11-12 04:16:32',
                'updated_at' => '2025-11-12 04:16:32',
                'deleted_at' => null,
                'reversal_of_id' => null,
                'head_date' => '2025-11-12 01:16:32',
                'ref' => null,
            ],
            [
                'id' => 22,
                'entry_date' => '2025-10-07',
                'reference' => null,
                'description' => 'عياس العيسي - تحويل مبلغ 35000 من مبلغ التقبيل مكتب الامتياز فرع الربوه متبقي نصف المبلغ',
                'created_by' => 160,
                'payment_voucher_id' => null,
                'type' => 'entry',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-11-12 04:21:07',
                'updated_at' => '2025-11-12 04:21:07',
                'deleted_at' => null,
                'reversal_of_id' => null,
                'head_date' => '2025-11-12 01:21:07',
                'ref' => null,
            ],
            [
                'id' => 23,
                'entry_date' => '2025-10-08',
                'reference' => null,
                'description' => 'دفعة من مساند',
                'created_by' => 160,
                'payment_voucher_id' => null,
                'type' => 'entry',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-11-12 04:26:18',
                'updated_at' => '2025-11-12 04:26:18',
                'deleted_at' => null,
                'reversal_of_id' => null,
                'head_date' => '2025-11-12 01:26:18',
                'ref' => null,
            ],
            [
                'id' => 24,
                'entry_date' => '2025-10-08',
                'reference' => null,
                'description' => 'راكان نوار محمد المطيري - مطالبة مالية رجالية علي يوزر الامتياز',
                'created_by' => 160,
                'payment_voucher_id' => null,
                'type' => 'entry',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-11-12 04:35:28',
                'updated_at' => '2025-11-12 04:35:28',
                'deleted_at' => null,
                'reversal_of_id' => null,
                'head_date' => '2025-11-12 01:35:28',
                'ref' => null,
            ],
            [
                'id' => 25,
                'entry_date' => '2025-10-08',
                'reference' => null,
                'description' => ''مندوبة الفلبين ANALYN FISHER - ادخال 3 عقود للبولو2 امتياز+1 انجاز (نايف السيف+محمد سلمان+منال الحميد',
            ],
            [
                'id' => 26,
                'entry_date' => '2025-10-08',
                'reference' => null,
                'description' => 'رواتب مكتب الإنجاز شهر سبتمبر',
                'created_by' => 160,
                'payment_voucher_id' => null,
                'type' => 'entry',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-11-12 04:54:49',
                'updated_at' => '2025-11-12 04:54:49',
                'deleted_at' => null,
                'reversal_of_id' => null,
                'head_date' => '2025-11-12 01:54:49',
                'ref' => null,
            ],
            [
                'id' => 27,
                'entry_date' => '2025-10-08',
                'reference' => null,
                'description' => 'سداد دراسة الجدوى ترخيص مكتب العمل - يوسف سداد بطاقة ائتمانية 7808',
                'created_by' => 160,
                'payment_voucher_id' => null,
                'type' => 'entry',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-11-12 04:56:25',
                'updated_at' => '2025-11-12 04:56:25',
                'deleted_at' => null,
                'reversal_of_id' => null,
                'head_date' => '2025-11-12 01:56:25',
                'ref' => null,
            ],
            [
                'id' => 28,
                'entry_date' => '2025-10-09',
                'reference' => null,
                'description' => 'استرداد من الموظفة نجلاء',
                'created_by' => 160,
                'payment_voucher_id' => null,
                'type' => 'entry',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-11-12 05:50:37',
                'updated_at' => '2025-11-12 05:50:37',
                'deleted_at' => null,
                'reversal_of_id' => null,
                'head_date' => '2025-11-12 02:50:37',
                'ref' => null,
            ],
            [
                'id' => 29,
                'entry_date' => '2025-10-09',
                'reference' => null,
                'description' => 'تامينات مؤسسة سلطان',
                'created_by' => 160,
                'payment_voucher_id' => null,
                'type' => 'entry',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-11-12 06:04:01',
                'updated_at' => '2025-11-12 06:04:01',
                'deleted_at' => null,
                'reversal_of_id' => null,
                'head_date' => '2025-11-12 03:04:01',
                'ref' => null,
            ],
            [
                'id' => 30,
                'entry_date' => '2025-10-09',
                'reference' => null,
                'description' => 'عهدة فيزا رقم 9748',
                'created_by' => 160,
                'payment_voucher_id' => null,
                'type' => 'entry',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-11-12 06:08:41',
                'updated_at' => '2025-11-12 06:08:41',
                'deleted_at' => null,
                'reversal_of_id' => null,
                'head_date' => '2025-11-12 03:08:41',
                'ref' => null,
            ],
            [
                'id' => 31,
                'entry_date' => '2025-10-11',
                'reference' => null,
                'description' => 'عهدة فيزا 9151',
                'created_by' => 160,
                'payment_voucher_id' => null,
                'type' => 'entry',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-11-12 06:14:45',
                'updated_at' => '2025-11-12 06:14:45',
                'deleted_at' => null,
                'reversal_of_id' => null,
                'head_date' => '2025-11-12 03:14:45',
                'ref' => null,
            ],
            [
                'id' => 32,
                'entry_date' => '2025-10-12',
                'reference' => null,
                'description' => 'محمود عاصم - طباعة خطه العمل وتغليفها لتقديمها لمكتب العمل',
                'created_by' => 160,
                'payment_voucher_id' => null,
                'type' => 'entry',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-11-12 06:16:21',
                'updated_at' => '2025-11-12 06:16:21',
                'deleted_at' => null,
                'reversal_of_id' => null,
                'head_date' => '2025-11-12 03:16:21',
                'ref' => null,
            ],
            [
                'id' => 33,
                'entry_date' => '2025-10-12',
                'reference' => null,
                'description' => 'فيصل مترجم عرعر - سداد رخصة العمل 12 شهور تخصم مناصفه',
                'created_by' => 160,
                'payment_voucher_id' => null,
                'type' => 'entry',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-11-12 06:26:55',
                'updated_at' => '2025-11-12 06:26:55',
                'deleted_at' => null,
                'reversal_of_id' => null,
                'head_date' => '2025-11-12 03:26:55',
                'ref' => null,
            ],
            [
                'id' => 34,
                'entry_date' => '2025-10-13',
                'reference' => null,
                'description' => 'دفعة من مساند',
                'created_by' => 160,
                'payment_voucher_id' => null,
                'type' => 'entry',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-11-12 06:31:35',
                'updated_at' => '2025-11-12 06:31:35',
                'deleted_at' => null,
                'reversal_of_id' => null,
                'head_date' => '2025-11-12 03:31:35',
                'ref' => null,
            ],
            [
                'id' => 35,
                'entry_date' => '2025-10-14',
                'reference' => null,
                'description' => 'عياس العيسي - تحويل مبلغ 35000 المتبقي من مبلغ التقبيل مكتب الامتياز فرع الربوه الإجمالي 70000 ريال',
                'created_by' => 160,
                'payment_voucher_id' => null,
                'type' => 'entry',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-11-12 06:47:58',
                'updated_at' => '2025-11-12 06:47:58',
                'deleted_at' => null,
                'reversal_of_id' => null,
                'head_date' => '2025-11-12 03:47:58',
                'ref' => null,
            ],
            [
                'id' => 36,
                'entry_date' => '2025-10-14',
                'reference' => null,
                'description' => 'مشاعل صالح سفر النفيعي - مطالبه ماليه علي يوزر الإنجاز',
                'created_by' => 160,
                'payment_voucher_id' => null,
                'type' => 'entry',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-11-12 06:56:05',
                'updated_at' => '2025-11-12 06:56:05',
                'deleted_at' => null,
                'reversal_of_id' => null,
                'head_date' => '2025-11-12 03:56:05',
                'ref' => null,
            ],
            [
                'id' => 37,
                'entry_date' => '2025-10-15',
                'reference' => null,
                'description' => 'ايراد من العميل عبد الرحمن',
                'created_by' => 160,
                'payment_voucher_id' => null,
                'type' => 'entry',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-11-12 07:20:25',
                'updated_at' => '2025-11-12 07:20:25',
                'deleted_at' => null,
                'reversal_of_id' => null,
                'head_date' => '2025-11-12 04:20:25',
                'ref' => null,
            ],
            [
                'id' => 38,
                'entry_date' => '2025-10-15',
                'reference' => null,
                'description' => ''مندوبة الفلبين ANALYN FISHER - ادخال 5عقود للبولو2متميز +2 امتياز+1 انجاز (عبدالله لواص+طلال الرويلي+عبدالله العنزي+هديه الشمري+وليد الديب',
            ],
            [
                'id' => 39,
                'entry_date' => '2025-10-16',
                'reference' => null,
                'description' => 'شحن فيزا رقم 9151',
                'created_by' => 160,
                'payment_voucher_id' => null,
                'type' => 'entry',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-11-12 07:35:57',
                'updated_at' => '2025-11-12 07:35:57',
                'deleted_at' => null,
                'reversal_of_id' => null,
                'head_date' => '2025-11-12 04:35:57',
                'ref' => null,
            ],
            [
                'id' => 40,
                'entry_date' => '2025-10-18',
                'reference' => null,
                'description' => 'شحن فيزا رقم 9748',
                'created_by' => 160,
                'payment_voucher_id' => null,
                'type' => 'entry',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-11-12 07:37:34',
                'updated_at' => '2025-11-12 07:37:34',
                'deleted_at' => null,
                'reversal_of_id' => null,
                'head_date' => '2025-11-12 04:37:34',
                'ref' => null,
            ],
            [
                'id' => 41,
                'entry_date' => '2025-10-19',
                'reference' => null,
                'description' => 'عهدة فيزا 9151 - شحن',
                'created_by' => 160,
                'payment_voucher_id' => null,
                'type' => 'entry',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-11-12 15:42:05',
                'updated_at' => '2025-11-12 15:42:05',
                'deleted_at' => null,
                'reversal_of_id' => null,
                'head_date' => '2025-11-12 12:42:05',
                'ref' => null,
            ],
            [
                'id' => 42,
                'entry_date' => '2025-10-19',
                'reference' => null,
                'description' => 'مؤسسه خيال الزاهر - فك وتركيب زجاج لمكتب الجديد الربوه تعديل مكتب ابوسلطان وغرفة الاجتماعات الإجمالي 2875 تحويل 1500 ريال',
                'created_by' => 160,
                'payment_voucher_id' => null,
                'type' => 'entry',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-11-12 15:44:18',
                'updated_at' => '2025-11-12 15:44:18',
                'deleted_at' => null,
                'reversal_of_id' => null,
                'head_date' => '2025-11-12 12:44:18',
                'ref' => null,
            ],
            [
                'id' => 43,
                'entry_date' => '2025-10-20',
                'reference' => null,
                'description' => 'دفعة من مساند',
                'created_by' => 160,
                'payment_voucher_id' => null,
                'type' => 'entry',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-11-12 15:47:03',
                'updated_at' => '2025-11-12 15:47:03',
                'deleted_at' => null,
                'reversal_of_id' => null,
                'head_date' => '2025-11-12 12:47:03',
                'ref' => null,
            ],
            [
                'id' => 44,
                'entry_date' => '2025-10-20',
                'reference' => null,
                'description' => 'سداد فاتورة مكتب نيشن سريلانكا',
                'created_by' => 160,
                'payment_voucher_id' => null,
                'type' => 'entry',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-11-12 16:10:48',
                'updated_at' => '2025-11-12 16:10:48',
                'deleted_at' => null,
                'reversal_of_id' => null,
                'head_date' => '2025-11-12 13:10:48',
                'ref' => null,
            ],
            [
                'id' => 45,
                'entry_date' => '2025-10-21',
                'reference' => null,
                'description' => 'دفعة من مساند',
                'created_by' => 160,
                'payment_voucher_id' => null,
                'type' => 'entry',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-11-12 16:37:38',
                'updated_at' => '2025-11-12 16:37:38',
                'deleted_at' => null,
                'reversal_of_id' => null,
                'head_date' => '2025-11-12 13:37:38',
                'ref' => null,
            ],
            [
                'id' => 46,
                'entry_date' => '2025-10-21',
                'reference' => null,
                'description' => 'ابوفواز - تحويل رسوم استلام عاملات من شركة سلسك الدمام 167 ريال +رسوم المندوب 150 ريال اماني رمضان الظفيري',
                'created_by' => 160,
                'payment_voucher_id' => null,
                'type' => 'entry',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-11-12 16:50:41',
                'updated_at' => '2025-11-12 16:50:41',
                'deleted_at' => null,
                'reversal_of_id' => null,
                'head_date' => '2025-11-12 13:50:41',
                'ref' => null,
            ],
            [
                'id' => 47,
                'entry_date' => '2025-10-22',
                'reference' => null,
                'description' => 'دفعة من مساند',
                'created_by' => 160,
                'payment_voucher_id' => null,
                'type' => 'entry',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-11-12 16:54:40',
                'updated_at' => '2025-11-12 16:54:40',
                'deleted_at' => null,
                'reversal_of_id' => null,
                'head_date' => '2025-11-12 13:54:40',
                'ref' => null,
            ],
            [
                'id' => 48,
                'entry_date' => '2025-10-22',
                'reference' => null,
                'description' => 'فاطمه عطيه حزيم العنزي - سداد الإقامة - العاملة نقل الي العميل حنان حليس الشمري مسدد 2000 ريال باقي 7000 تم اصدار كمبيالة',
                'created_by' => 160,
                'payment_voucher_id' => null,
                'type' => 'entry',
                'branch_id' => 1,
                'asset_id' => null,
                'reversal' => 1,
                'created_at' => '2025-11-12 17:10:14',
                'updated_at' => '2025-11-12 17:10:14',
                'deleted_at' => null,
                'reversal_of_id' => null,
                'head_date' => '2025-11-12 14:10:14',
                'ref' => null,
            ],
            [
                'id' => '`id` bigint(20',
            ],
            [
                'id' => 20,
            ],
            [
                'id' => 20,
            ],
            [
                'id' => 15,
                'entry_date' => 2,
            ],
            [
                'id' => 15,
                'entry_date' => 2,
            ],
            [
                'id' => 20,
            ],
            [
                'id' => 255,
            ],
            [
                'id' => 20,
            ],
            [
                'id' => 20,
            ],
        ];

        foreach ($data as $row) {
            DB::table('journal_entries')->insert($row);
        }

        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
