<?php

namespace Database\Seeders\AuthAndUserManagement;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AdminsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('admins')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        // Get existing IDs to validate foreign keys
        $existingDepartmentIds = DB::table('departments')->pluck('id')->toArray();
        $existingBranchIds = DB::table('branches')->pluck('id')->toArray();
        $existingRoleIds = DB::table('roles')->pluck('id')->toArray();

        $admins = [
            [
                'id' => 100,
                'local_id' => 100,
                'f_name' => 'admin',
                'l_name' => 'Aa12345',
                'name_en' => '',
                'email' => 'info@novoosystem.com',
                'phone' => null,
                'password' => '$2y$10$cS/TR8WC0kTuIn4unbJdi.4RqNMfX/F3TcpWajrCwnSQzr5fFgDeC',
                'remember_token' => null,
                'insert_flag' => 1,
                'created_at' => '2023-12-24 18:27:14',
                'update_flag' => 0,
                'updated_at' => '2025-09-09 17:31:13',
                'image' => '2025-02-19-67b500022451f.png',
                'company_id' => null,
                'mandob_code' => null,
                'vehicle_code' => null,
                'type' => null,
                'role' => 'admin',
                'dashboard' => 0,
                'pos' => 0,
                'stock' => 0,
                'store' => 0,
                'cat' => 0,
                'unit' => 0,
                'product' => 0,
                'stock_limit' => 0,
                'coupons' => 0,
                'customer' => 0,
                'seller' => 0,
                'admin' => 0,
                'supplier' => 0,
                'setting' => 0,
                'requests' => 0,
                'storage' => 0,
                'notification' => 0,
                'tracking' => 0,
                'vehicle_stock' => 0,
                'reports' => 0,
                'regions' => 0,
                'sales' => 1,
                'accounts' => 1,
                'rating' => 1,
                'visit' => 1,
                'sectionsalary' => 1,
                'latitude' => '1',
                'longitude' => '1',
                'visitors' => 0,
                'result_visitors' => 0,
                'salary' => '0',
                'precent_of_sales' => '0',
                'commission' => '0',
                'balance' => '0',
                'credit' => '0',
                'loan' => 0,
                'score' => '0',
                'note' => '',
                'holidays' => 0,
                'number_of_days' => 0,
                'role_id' => 1,
                'branch_id' => 1,
                'shift_id' => '["1","2"]',
                'account_id' => null,
                'department_id' => 1,
                'manager_id' => null,
                'deleted_at' => '2025-09-09 17:31:13',
            ],
            [
                'id' => 159,
                'local_id' => 0,
                'f_name' => 'محمود',
                'l_name' => 'بشير',
                'name_en' => 'Default Name',
                'email' => 'mahmoudbeshier@alemtayaz.com',
                'phone' => null,
                'password' => '$2y$10$ZiuXBrVzZAJAHUnzu1I2GOMXgX.fjP.mVI..vW0F9YI1zH6yvhpEK',
                'remember_token' => null,
                'insert_flag' => 1,
                'created_at' => '2025-08-30 16:02:31',
                'update_flag' => 0,
                'updated_at' => '2025-09-09 18:04:06',
                'image' => null,
                'company_id' => 1,
                'mandob_code' => null,
                'vehicle_code' => null,
                'type' => null,
                'role' => 'admin',
                'dashboard' => 0,
                'pos' => 0,
                'stock' => 0,
                'store' => 0,
                'cat' => 0,
                'unit' => 0,
                'product' => 0,
                'stock_limit' => 0,
                'coupons' => 0,
                'customer' => 0,
                'seller' => 0,
                'admin' => 0,
                'supplier' => 0,
                'setting' => 0,
                'requests' => 0,
                'storage' => 0,
                'notification' => 0,
                'tracking' => 0,
                'vehicle_stock' => 0,
                'reports' => 0,
                'regions' => 0,
                'sales' => 1,
                'accounts' => 1,
                'rating' => 1,
                'visit' => 1,
                'sectionsalary' => 1,
                'latitude' => null,
                'longitude' => null,
                'visitors' => 0,
                'result_visitors' => 0,
                'salary' => '0',
                'precent_of_sales' => '0',
                'commission' => '0',
                'balance' => '0',
                'credit' => '0',
                'loan' => 0,
                'score' => '0',
                'note' => '\'\'',
                'holidays' => 0,
                'number_of_days' => 0,
                'role_id' => 3,
                'branch_id' => 1,
                'shift_id' => '1',
                'account_id' => null,
                'department_id' => 4,
                'manager_id' => 160,
                'deleted_at' => null,
            ],
            [
                'id' => 160,
                'local_id' => 0,
                'f_name' => 'محمود',
                'l_name' => 'عاصم',
                'name_en' => 'Default Name',
                'email' => 'mahmoudassem@alemtayaz.com',
                'phone' => null,
                'password' => '$2y$10$E31iiaILRPPH2LAvKvUM8uglRMjpXeBi/bZ2aOQ/luXcmXXHivZum',
                'remember_token' => null,
                'insert_flag' => 1,
                'created_at' => '2025-08-30 16:03:14',
                'update_flag' => 0,
                'updated_at' => '2025-09-09 18:04:37',
                'image' => null,
                'company_id' => 1,
                'mandob_code' => null,
                'vehicle_code' => null,
                'type' => null,
                'role' => 'admin',
                'dashboard' => 0,
                'pos' => 0,
                'stock' => 0,
                'store' => 0,
                'cat' => 0,
                'unit' => 0,
                'product' => 0,
                'stock_limit' => 0,
                'coupons' => 0,
                'customer' => 0,
                'seller' => 0,
                'admin' => 0,
                'supplier' => 0,
                'setting' => 0,
                'requests' => 0,
                'storage' => 0,
                'notification' => 0,
                'tracking' => 0,
                'vehicle_stock' => 0,
                'reports' => 0,
                'regions' => 0,
                'sales' => 1,
                'accounts' => 1,
                'rating' => 1,
                'visit' => 1,
                'sectionsalary' => 1,
                'latitude' => null,
                'longitude' => null,
                'visitors' => 0,
                'result_visitors' => 0,
                'salary' => '0',
                'precent_of_sales' => '0',
                'commission' => '0',
                'balance' => '0',
                'credit' => '0',
                'loan' => 0,
                'score' => '0',
                'note' => '\'\'',
                'holidays' => 0,
                'number_of_days' => 0,
                'role_id' => 1,
                'branch_id' => 1,
                'shift_id' => '1',
                'account_id' => null,
                'department_id' => 4,
                'manager_id' => 164,
                'deleted_at' => null,
            ],
            [
                'id' => 161,
                'local_id' => 0,
                'f_name' => 'مصطفي',
                'l_name' => 'خطاب',
                'name_en' => 'Default Name',
                'email' => 'mostafakhatab@alemtayaz.com',
                'phone' => null,
                'password' => '$2y$10$5brJMtfNoIQ5.MJrzh6eB.b/Ab2SqZN939H5SiDZwf10baejdfa/G',
                'remember_token' => null,
                'insert_flag' => 1,
                'created_at' => '2025-08-30 16:03:54',
                'update_flag' => 0,
                'updated_at' => '2025-09-09 18:05:08',
                'image' => null,
                'company_id' => 1,
                'mandob_code' => null,
                'vehicle_code' => null,
                'type' => null,
                'role' => 'admin',
                'dashboard' => 0,
                'pos' => 0,
                'stock' => 0,
                'store' => 0,
                'cat' => 0,
                'unit' => 0,
                'product' => 0,
                'stock_limit' => 0,
                'coupons' => 0,
                'customer' => 0,
                'seller' => 0,
                'admin' => 0,
                'supplier' => 0,
                'setting' => 0,
                'requests' => 0,
                'storage' => 0,
                'notification' => 0,
                'tracking' => 0,
                'vehicle_stock' => 0,
                'reports' => 0,
                'regions' => 0,
                'sales' => 1,
                'accounts' => 1,
                'rating' => 1,
                'visit' => 1,
                'sectionsalary' => 1,
                'latitude' => null,
                'longitude' => null,
                'visitors' => 0,
                'result_visitors' => 0,
                'salary' => '0',
                'precent_of_sales' => '0',
                'commission' => '0',
                'balance' => '0',
                'credit' => '0',
                'loan' => 0,
                'score' => '0',
                'note' => '\'\'',
                'holidays' => 0,
                'number_of_days' => 0,
                'role_id' => 4,
                'branch_id' => 1,
                'shift_id' => '1',
                'account_id' => null,
                'department_id' => 8,
                'manager_id' => 165,
                'deleted_at' => null,
            ],
            [
                'id' => 163,
                'local_id' => 0,
                'f_name' => 'ادمن',
                'l_name' => 'ادمن',
                'name_en' => 'Default Name',
                'email' => 'admin@alemtayaz.com',
                'phone' => null,
                'password' => '$2y$10$gVVJwJzW5OxRv0EETXDaBu3oh.UanF/lxhLOFJOduGLwWczN9Y1pS',
                'remember_token' => null,
                'insert_flag' => 1,
                'created_at' => '2025-09-09 17:20:36',
                'update_flag' => 0,
                'updated_at' => '2025-09-09 18:03:39',
                'image' => null,
                'company_id' => 1,
                'mandob_code' => null,
                'vehicle_code' => null,
                'type' => null,
                'role' => 'admin',
                'dashboard' => 0,
                'pos' => 0,
                'stock' => 0,
                'store' => 0,
                'cat' => 0,
                'unit' => 0,
                'product' => 0,
                'stock_limit' => 0,
                'coupons' => 0,
                'customer' => 0,
                'seller' => 0,
                'admin' => 0,
                'supplier' => 0,
                'setting' => 0,
                'requests' => 0,
                'storage' => 0,
                'notification' => 0,
                'tracking' => 0,
                'vehicle_stock' => 0,
                'reports' => 0,
                'regions' => 0,
                'sales' => 1,
                'accounts' => 1,
                'rating' => 1,
                'visit' => 1,
                'sectionsalary' => 1,
                'latitude' => null,
                'longitude' => null,
                'visitors' => 0,
                'result_visitors' => 0,
                'salary' => '0',
                'precent_of_sales' => '0',
                'commission' => '0',
                'balance' => '0',
                'credit' => '0',
                'loan' => 0,
                'score' => '0',
                'note' => '\'\'',
                'holidays' => 0,
                'number_of_days' => 0,
                'role_id' => 2,
                'branch_id' => 1,
                'shift_id' => '1',
                'account_id' => null,
                'department_id' => null,
                'manager_id' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 164,
                'local_id' => 0,
                'f_name' => 'ابو',
                'l_name' => 'سلطان',
                'name_en' => 'Default Name',
                'email' => 'ceo@alemtayaz.com',
                'phone' => null,
                'password' => '$2y$10$IXOHPQBm5P94v4eIiDpwKOQpW/.FG0LqIvPfpaSBy3/hIwIfBwbIu',
                'remember_token' => null,
                'insert_flag' => 1,
                'created_at' => '2025-09-09 17:38:12',
                'update_flag' => 0,
                'updated_at' => '2025-09-09 17:38:12',
                'image' => null,
                'company_id' => 1,
                'mandob_code' => null,
                'vehicle_code' => null,
                'type' => null,
                'role' => 'admin',
                'dashboard' => 0,
                'pos' => 0,
                'stock' => 0,
                'store' => 0,
                'cat' => 0,
                'unit' => 0,
                'product' => 0,
                'stock_limit' => 0,
                'coupons' => 0,
                'customer' => 0,
                'seller' => 0,
                'admin' => 0,
                'supplier' => 0,
                'setting' => 0,
                'requests' => 0,
                'storage' => 0,
                'notification' => 0,
                'tracking' => 0,
                'vehicle_stock' => 0,
                'reports' => 0,
                'regions' => 0,
                'sales' => 1,
                'accounts' => 1,
                'rating' => 1,
                'visit' => 1,
                'sectionsalary' => 1,
                'latitude' => null,
                'longitude' => null,
                'visitors' => 0,
                'result_visitors' => 0,
                'salary' => '0',
                'precent_of_sales' => '0',
                'commission' => '0',
                'balance' => '0',
                'credit' => '0',
                'loan' => 0,
                'score' => '0',
                'note' => '\'\'',
                'holidays' => 0,
                'number_of_days' => 0,
                'role_id' => 2,
                'branch_id' => 1,
                'shift_id' => '1',
                'account_id' => null,
                'department_id' => null,
                'manager_id' => null,
                'deleted_at' => null,
            ],
        ];

        // Validate and fix foreign key values
        foreach ($admins as &$admin) {
            // Validate department_id
            if (isset($admin['department_id']) && $admin['department_id'] !== null) {
                if (!in_array($admin['department_id'], $existingDepartmentIds)) {
                    // Department doesn't exist, set to null
                    $admin['department_id'] = null;
                }
            }
            
            // Validate branch_id
            if (isset($admin['branch_id']) && $admin['branch_id'] !== null) {
                if (!in_array($admin['branch_id'], $existingBranchIds)) {
                    // Branch doesn't exist, set to null or default to 1 if exists
                    $admin['branch_id'] = !empty($existingBranchIds) ? $existingBranchIds[0] : null;
                }
            }
            
            // Validate role_id
            if (isset($admin['role_id']) && $admin['role_id'] !== null) {
                if (!in_array($admin['role_id'], $existingRoleIds)) {
                    // Role doesn't exist, set to null or default to first role if exists
                    $admin['role_id'] = !empty($existingRoleIds) ? $existingRoleIds[0] : null;
                }
            }
            
            // manager_id is self-referencing, will be validated after first insert
            // For now, we'll set it to null if the manager doesn't exist in our array
            if (isset($admin['manager_id']) && $admin['manager_id'] !== null) {
                $managerExists = false;
                foreach ($admins as $checkAdmin) {
                    if (isset($checkAdmin['id']) && $checkAdmin['id'] == $admin['manager_id']) {
                        $managerExists = true;
                        break;
                    }
                }
                if (!$managerExists) {
                    // Manager doesn't exist in our seed data, set to null
                    $admin['manager_id'] = null;
                }
            }
        }
        unset($admin); // Break the reference

        // Insert in chunks
        foreach (array_chunk($admins, 100) as $chunk) {
            DB::table('admins')->insert($chunk);
        }

        // Note: Add more admin data from the SQL file as needed
    }
}
